bmnc12/bmnc12/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
import beranda.urls as beranda

urlpatterns = [
    path('login/', include(('login.urls', 'login'), namespace="login")),
    path('registrasi/', include(('registrasi.urls', 'registrasi'), namespace="registrasi")),
    path('buat-berita/', include(('buat_berita.urls', 'buat_berita'), namespace="buat_berita")),
    path('polling-biasa/', include(('polling_biasa.urls', 'polling_biasa'), namespace="polling_biasa")),
    path('polling-berita/', include(('polling_berita.urls', 'polling_berita'), namespace="polling_berita")),
    path('personal-profile/', include(('personal_profile.urls', 'personal_profile'), namespace="personal_profile")),
    path('lihat-polling/', include(('lihat_polling.urls', 'lihat_polling'), namespace="lihat_polling")),
    path('', include(('beranda.urls', 'beranda'), namespace="")),
]

bmnc12/login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('otologin', views.otorisasi_login, name='otologin'),
    path('otologout', views.otorisasi_logout, name='otologout'),
]

bmnc12/polling_biasa/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('polling_biasa', polling_biasa,name='polling_biasa'),
]

bmnc12/polling_biasa/models.py
from django.db import models

# Create your models here.

bmnc12/polling_biasa/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.hashers import *
from django.db import connection,transaction
from core.models import Polling
        
def index(request):
    response = {}
    if 'bmnc_user_login' in request.session.keys():
        response["masuk"] = True
        response["adalah_narasumber"] = request.session["adalah_narasumber"]
        if response["adalah_narasumber"]:
            return render(request, 'polling_biasa/polling_biasa.html', response)
        else:
            messages.error(request, "Maaf, anda bukan Narasumber")
            return HttpResponseRedirect(reverse("beranda:index"))
    else:
        return HttpResponseRedirect(reverse("login:index"))

def polling_biasa(request):
    if(request.method == 'POST'):
        req = request.POST
        deskripsi = req["Deskripsi"].strip()
        mulai = req["Mulai"].strip()
        selesai = req["Selesai"].strip()
        url = "http://localhost:8000/polling-biasa/"
        i_user = 0
        for i in Polling.objects.raw("SELECT id FROM POLLING"):
            i_user = i.id
        i_user += 1
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO POLLING(id,polling_start,polling_end,total_responden) "
                           + "VALUES (%s,%s,%s,%s)", [i_user,mulai,selesai,1]);
            cursor.execute("INSERT INTO POLLING_BIASA(id_polling,url,deskripsi) "
                           + "VALUES (%s,%s,%s)", [i_user,url,deskripsi]);
        return HttpResponseRedirect(reverse("beranda:index"))

bmnc12/polling_biasa/templates/polling_biasa/polling_biasa.html
{% extends "general/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block head_css_after %}
    <title>Buat Polling Biasa - BMNC</title>
{% endblock %}

{% block content %}
<div class="py-5" style="background-image: url({% static "general/bg-regis.jpg" %});">
    <div class="container">
        <i>
            {% for message in messages %}
            <label style="position:relative; right:0px; text-align: right; display: block;" class="text-danger">
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
                {{ message }}
            </label><br>
            {% endfor %}
        </i>
        <div class="row">
            <div class="col-md-12">
                <form action="{% url 'polling_biasa:polling_biasa' %}" method="POST" >
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Deskripsi</label>
                        <input type="text" name = "Deskripsi" class="form-control" placeholder="Deskripsi"> </div>
                    <div class="form-group">
                        <label>Waktu Mulai</label>
                        <input type="date" name="Mulai" class="form-control"> </div>
                    <div class="form-group">
                        <label>Waktu Selesai</label>
                        <input type="date" name = "Selesai" class="form-control"> </div>
                    <div class="form-group">
                        <label>Apa itu Polling?</label>
                        <input type="text" name="" class="form-control" placeholder="jawaban"> </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}