bmnc12/bmnc12/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
import beranda.urls as beranda

urlpatterns = [
    path('login/', include(('login.urls', 'login'), namespace="login")),
    path('registrasi/', include(('registrasi.urls', 'registrasi'), namespace="registrasi")),
    path('buat-berita/', include(('buat_berita.urls', 'buat_berita'), namespace="buat_berita")),
    path('polling-biasa/', include(('polling_biasa.urls', 'polling_biasa'), namespace="polling_biasa")),
    path('polling-berita/', include(('polling_berita.urls', 'polling_berita'), namespace="polling_berita")),
    path('personal-profile/', include(('personal_profile.urls', 'personal_profile'), namespace="personal_profile")),
    path('lihat-polling/', include(('lihat_polling.urls', 'lihat_polling'), namespace="lihat_polling")),
    path('', include(('beranda.urls', 'beranda'), namespace="")),
]

bmnc12/login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('otologin', views.otorisasi_login, name='otologin'),
    path('otologout', views.otorisasi_logout, name='otologout'),
]

bmnc12/registrasi/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('registrasi', views.registrasi, name='registrasi'),
    path('cek-noid-ada', views.cek_nomor_identitas_ada_ajax, name='cek_noid_ada'),
    path('cek-username-ada', views.cek_username_ada_ajax, name='cek_username_ada'),
]

bmnc12/registrasi/models.py
from django.db import models

# Create your models here.

bmnc12/registrasi/views.py
from django.shortcuts import render
from django.urls import reverse
from core.models import Universitas, Narasumber, Pengguna
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth.hashers import *
from django.views.decorators.csrf import csrf_exempt
import json, re, datetime

from django.db import connection,transaction

listUniv = Universitas.objects.raw("SELECT id FROM UNIVERSITAS");
response = {"daftar_univ": listUniv}
kepanjangan_jabatan = {"M": "MAHASISWA", "D":"DOSEN", "S":"STAF"}
elemen_form = ('nama', 'jabatan', 'username', 'nomor-identitas',
    'tempat-lahir', 'tanggal-lahir', 'email',  'status', 'id-universitas');

def index(request):
    response["jumlah_narasumber"] = 0
    with connection.cursor() as cursor:
        cursor.execute("SELECT id FROM NARASUMBER")
        row = cursor.fetchall()
        if row is not None:
            response["jumlah_narasumber"] = len(row)
            
    if "bmnc_user_login" not in request.session.keys():
        response["render_masuk"] = True
    return render(request, 'registrasi/halaman-registrasi.html', response)
    
def registrasi(request):
    if(request.method == 'POST'):
        req = request.POST
        
        # Validasi semua nilai yang dibutuhkan terisi
        
        hasil_cek = cek_setiap_key_ada(req)
        
        # Validasi password
        
        if hasil_cek is not None:
            messages.error(request, "Maaf, semua field selain nomor HP harus diisi")
            return HttpResponseRedirect(reverse("registrasi:index"))
        
        # Validasi username
        
        username = req["username"].strip()
        password = req["password"]
        no_id    = req["nomor-identitas"].strip()
        
        if cek_username_ada(username):
            messages.error(request, "Maaf, username sudah ada")
            return HttpResponseRedirect(reverse("registrasi:index"))
        
        if not cek_username_valid(username):
            messages.error(request, "Maaf, username tidak valid")
            return HttpResponseRedirect(reverse("registrasi:index"))
    
        if not cek_password_valid(password):
            messages.error(request, "Maaf, password minimal 8 karakter")
            return HttpResponseRedirect(reverse("registrasi:index"))
        
        # Validasi nomor identitas
        
        if cek_nomor_identitas_ada(no_id, kepanjangan_jabatan[req["jabatan"]]):
            messages.error(request, "Maaf, nomor identitas sudah ada")
            return HttpResponseRedirect(reverse("registrasi:index"))
        
        if not cek_nomor_identitas_valid(no_id):
            messages.error(request, "Maaf, nomor identitas harus digit")
            return HttpResponseRedirect(reverse("registrasi:index"))
            
        # Validasi email
        
        if not cek_email_valid(req['email']):
            messages.error(request, "Maaf, email tidak valid")
            return HttpResponseRedirect(reverse("registrasi:index"))
        
        # Validasi tanggal
        
        if not cek_tanggal_valid(req['tanggal-lahir']):
            messages.error(request, "Maaf, tanggal lahir tidak valid")
            return HttpResponseRedirect(reverse("registrasi:index"))
        
        
        # Menentukan id narasumber baru untuk user ini

        i_user = 0
        for i in Pengguna.objects.raw("SELECT id FROM PENGGUNA"):
            i_user = i.id       
        
        i_user += 1
        password = req["password"]
        
        with connection.cursor() as cursor:
        
            # Memasukkan ke database pengguna
            
            cursor.execute("INSERT INTO PENGGUNA(id, username, role, password) "
            + "VALUES (%s, %s, %s, %s);", [i_user, username, "Narasumber", make_password(password)]);
            
            # Memasukkan ke database narasumber
            
            cursor.execute("INSERT INTO NARASUMBER(id,nama,email,tempat,tanggal,no_hp,"
            + "jumlah_berita,rerata_kata,id_universitas) VALUES (%s,%s,%s,%s,%s,%s,0,0,%s)",
            [i_user, req["nama"].strip(), req["email"].strip(), req["tempat-lahir"].strip(),
            req["tanggal-lahir"].strip(), req["no-hp"].strip(), req["id-universitas"].strip()]);
            
            # Memasukkan ke jabatan yang sesuai
            
            if req["jabatan"] == "M":
                cursor.execute("INSERT INTO MAHASISWA(id_narasumber,npm,status) "
                + "VALUES (%s,%s,%s)", [i_user, req["nomor-identitas"].strip(), req["status"].strip()])
            elif req["jabatan"] == "S":
                cursor.execute("INSERT INTO STAF(id_narasumber,nik_staf,posisi) "
                + "VALUES (%s,%s,%s)", [i_user, req["nomor-identitas"].strip(), req["status"].strip()])
            elif req["jabatan"] == "D":
                cursor.execute("INSERT INTO DOSEN(id_narasumber,nik_dosen,jurusan) "
                + "VALUES (%s,%s,%s)", [i_user, req["nomor-identitas"].strip(), req["status"].strip()])
                
        return render(request, 'registrasi/halaman-registrasi-berhasil.html', response)

def cek_username_ada(username):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM PENGGUNA WHERE username = %s", [username])
        return cursor.fetchone() is not None

def cek_username_valid(username):
    return all([i.isalnum() or i == '.' for i in username])

def cek_password_valid(password):
    return len(password) >= 8

def cek_nomor_identitas_valid(no_id):
    return all([i.isdigit() for i in no_id])

def cek_email_valid(email):
    return re.match(r"[^@]+@[^@]+\.[^@]+", email)

def cek_tanggal_valid(tanggal):
    try:
        datetime.datetime.strptime(tanggal, "%Y-%m-%d")
        return True
    except ValueError as e:
        return False

def cek_setiap_key_ada(req):
    try:
        for i in elemen_form:
            elem = req[i]
                
    except KeyError as e:
        return e.args[0]
        
def cek_nomor_identitas_ada(nomor_identitas, jabatan):
    tabel, nomor = "", ""
    
    if jabatan.upper() == "STAF":
        tabel, nomor = "STAF", "nik_staf"
    elif jabatan.upper() == "DOSEN":
        tabel, nomor = "DOSEN", "nik_dosen"
    elif jabatan.upper() == "MAHASISWA":
        tabel, nomor = "MAHASISWA", "npm"
    else:
        return False
        
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM " + tabel + " WHERE " + nomor + " = %s", [nomor_identitas])
        return cursor.fetchone() is not None

@csrf_exempt
def cek_nomor_identitas_ada_ajax(request):
    if request.method == 'POST':
        nomor_identitas = request.POST['nomor_identitas']
        jabatan = kepanjangan_jabatan[request.POST['jabatan']]
        hasil = cek_nomor_identitas_ada(nomor_identitas, jabatan)
        return JsonResponse({'hasil': json.dumps(hasil)})

@csrf_exempt
def cek_username_ada_ajax(request):
    if request.method == 'POST':
        username = request.POST['username']
        hasil = cek_username_ada(username)
        return JsonResponse({'hasil': json.dumps(hasil)})

bmnc12/registrasi/templates/registrasi/halaman-registrasi-berhasil.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static "/general/theme.css" %}"> </head>

<body>
  <nav class="navbar navbar-expand-lg bg-primary navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'beranda:index' %}"">
        <img src="{% static "/general/BMNC Logo Putih.svg" %}" width="50" height="50" class="d-inline-block align-top mx-1" alt="">
        <b>&nbsp;Biru Merah News Corporation</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login:index' %}">
              <i class="fa d-inline fa-lg fa-sign-in"></i> Masuk</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="py-5" style="background-image: url('{% static "/general/bg-regis.jpg" %}');background-size:cover;background-repeat:space;">
    <div class="container">
      <div class="row">
        <div class="align-self-center col-md-6 text-white">
          
          <p class="lead" id="regis-subheader"><br><br>Pendaftaran berhasil!<br>Silahkan masuk ulang.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-dark text-white">
    <div class="container">
      <div class="row">
        <div class="p-4 col-md-6">
          <div class="col-md-12">
            <img class="img-fluid d-block" src="{% static "/general/BMNC Logo.svg" %}" width="120pt"> </div>
          <div class="row"> </div>
          <div class="row">
            <div class="col-md-12">
              <ul class="list-unstyled">
                <a href="{% url 'beranda:index' %}"" class="text-white">Beranda</a>
                <br>
                <a href="#" class="text-white">Tentang Kami</a>
                <br>
                <a href="#" class="text-white">Layanan</a>
                <br> </ul>
            </div>
          </div>
        </div>
        <div class="p-4 col-md-6">
          <h2 class="mb-4">Kontak</h2>
          <p>
            <a href="tel:+62 840 0840 0840" class="text-white">
              <i class="fa d-inline mr-3 text-secondary fa-phone"></i>+62 840 0840 0840</a>
          </p>
          <p>
            <a href="mailto:info@bmnc12.com" class="text-white">
              <i class="fa d-inline mr-3 text-secondary fa-envelope-o"></i>info@bmnc12.com</a>
          </p>
          <p>
            <a href="https://goo.gl/maps/MPqj51wBQSo" class="text-white" target="_blank">
              <i class="fa d-inline mr-3 fa-map-marker text-secondary"></i>Fakultas Ilmu Komputer, Universitas Indonesia </a>
            <br> </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 mt-3">
          <p class="text-center text-white">Hak Cipta © 2018 BMNC12 dilindungi undang-undang. </p>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script>
    $('#select-jabatan').on('change', function() {
    label_id = $('#form-label-nomor-id');
      if (this.value == 'M') {
        $('#form-status-label').text('Status Mahasiswa');
        $('#regis-groupstatus > input').attr("name", "status-mahasiswa");
        label_id.text('Nomor Identitas (NPM)');
      } else if (this.value == 'D') {
        $('#form-status-label').text('Jurusan Dosen');
        $('#regis-groupstatus > input').attr("name", "jurusan-dosen");
      } else if (this.value == 'S') {
        $('#form-status-label').text('Posisi Staf');
        $('#regis-groupstatus > input').attr("name", "posisi-staf");
      }
    })
  </script>
</body>

</html>

bmnc12/registrasi/templates/registrasi/halaman-registrasi.html
{% extends "general/layout/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<div class="py-5" style="background-image: url('{% static "/general/bg-regis.jpg" %}');background-size:cover;background-repeat:space;">
<div class="container">
  <div class="row">
    <div class="align-self-center col-md-6 text-white">
      <h1 class="text-md-left display-3 text-dark text-left">Buat Berita Sekarang! &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
        <br> </h1>
      <p class="lead" id="regis-subheader">Dan bergabung dengan {{jumlah_narasumber}} narasumber lainnya!</p>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-body p-5">
          <h3 class="pb-3">Registrasi</h3>
          <i>
            {% for message in messages %}
            <label style="position:relative; right:0px; text-align: right; display: block;" class="text-danger">
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
              {{ message }}
            </label><br>
            {% endfor %}
          </i>
          <form action="{% url 'registrasi:registrasi' %}"" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleInputEmail1">Jabatan</label>
            <label for="exampleInputEmail1" class="text-success">*</label>
            <select class="custom-control custom-select" id="select-jabatan" name="jabatan" required="">
              <option selected="" value="M">Mahasiswa</option>
              <option value="S">Staf</option>
              <option value="D">Dosen</option>
            </select>
          </div>
          <div class="form-group" id="regis-username">
            <label>Username</label>
            <label for="exampleInputEmail1" class="text-success">*</label>
            <span style="float:right;" ><i style="display:none" class="fas fa-spinner fa-spin"></i><span style="font-size:0.8em" class="text-danger"></span></span>
            <input class="form-control" name="username" required=""> </div>
          <div class="form-group" id="regis-password">
            <label>Kata Sandi</label>
            <label for="exampleInputEmail1" class="text-success">*</label>
            <span style="float:right;" ><span style="font-size:0.8em" class="text-danger"></span></span>
            <input class="form-control" name="password" type="password" required=""> </div>
          <div class="form-group" id="regis-noid">
            <label id="form-label-nomor-id">Nomor Identitas (NPM)</label>
            <label class="text-success" for="exampleInputEmail1">*</label>
            <span style="float:right;" ><i style="display:none" class="fas fa-spinner fa-spin"></i><span style="font-size:0.8em" class="text-danger"></span></span>
            <input class="form-control" type="text" name="nomor-identitas" required=""> </div>
          <div class="form-group">
            <label>Nama</label>
            <label class="text-success" for="exampleInputEmail1">*</label>
            <input class="form-control" name="nama" type="text" required=""> </div>
          <div class="form-group">
            <label>Tempat Lahir</label>
            <label class="text-success" for="exampleInputEmail1">*</label>
            <input type="text" class="form-control" name="tempat-lahir" required=""> </div>
          <div class="form-group" id="regis-tgl-lahir">
            <label>Tanggal Lahir</label>
            <label class="text-success" for="exampleInputEmail1">*</label>
            <span style="float:right;" ><span style="font-size:0.8em" class="text-danger"></span></span>
            <input type="date" class="form-control" name="tanggal-lahir" required=""> </div>
          <div class="form-group">
            <label>Email</label>
            <label class="text-success" for="exampleInputEmail1">*</label>
            <input type="email" class="form-control" name="email" required=""> </div>
          <div class="form-group" id="regis-nohp">
            <label>Nomor HP</label>
            <span style="float:right;" ><span style="font-size:0.8em" class="text-danger"></span></span>
            <input type="text" class="form-control" name="no-hp"> </div>
          <div class="form-group" id="regis-groupstatus">
            <label id="form-status-label">Status Kemahasiswaan</label>
            <label class="text-success" for="exampleInputEmail1">*</label>
            <input type="text" class="form-control" name="status" required=""> </div>
          <div class="form-group" id="regis-id-universitas">
            <label id="form-status-label">ID Universitas</label>
            <select class="custom-control custom-select" id="select-id-univ" name="id-universitas" required="">
              {% for univ in daftar_univ %}
              <option value="{{univ.id}}">{{univ.id}}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <i>
              <label style="position:relative; right:0px; text-align: right;
    display: block;" class="text-success">*Dibutuhkan</label>
            </i>
          </div>
          <button type="submit" class="btn mt-2 btn-outline-secondary">Registrasi</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

{% block javascript %}
<script>
$("document").ready(function() {
    var validasi_tanggal = function(tanggal) {
        return !isNaN(new Date(tanggal).getTime());
    }

    noid_jabatan_input = $("#regis-noid > input, #select-jabatan");
    
    password_notice = $("#regis-password > span > span");
    password_input = $("#regis-password > input");
    
    jabatan_input = $("#select-jabatan");
    
    username_loading = $("#regis-username > span > i");
    username_notice = $("#regis-username > span > span");
    username_input = $("#regis-username > input");
    
    noid_loading = $("#regis-noid > span > i");
    noid_notice = $("#regis-noid > span > span");
    noid_input = $("#regis-noid > input");
    
    tgl_lahir_notice = $("#regis-tgl-lahir > span > span");
    tgl_lahir_input = $("#regis-tgl-lahir > input");
    
    nohp_notice = $("#regis-nohp > span > span");
    nohp_input = $("#regis-nohp > input");
    
    jabatan_input.on('change', function() {
        label_id = $('#form-label-nomor-id');
        label_text = $('#form-status-label');
        if (this.value == 'M') {
            label_text.text('Status Mahasiswa');
            label_id.text('Nomor Identitas (NPM)');
        } else if (this.value == 'D') {
            label_text.text('Jurusan Dosen');
            label_id.text('Nomor Identitas (NIK)');
        } else if (this.value == 'S') {
            label_text.text('Posisi Staf');
            label_id.text('Nomor Identitas (NIK)');
        }
    });
    
    password_input.change(function () {
        if ($(this).val().length < 8) {
            password_notice.text("Password minimal 8 karakter");
        } else {
            password_notice.text("");
        }
        password_input.get(0).setCustomValidity(password_notice.text());
});
    
    username_input.change(function () {
        console.log($(this).val());
        username = $(this).val().trim();
        $(this).val(username);
        username_loading.show();
        username_notice.text("");        
        $.ajax({
            method: "POST",
            url: '{% url "registrasi:cek_username_ada" %}',
            data: {
                'username': username
            },
            dataType: 'json',
            success: function (response) {
                console.log(response);
                if (response["hasil"] === "true") {
                    username_notice.text("Username sudah ada");
                }
                username_input.get(0).setCustomValidity(username_notice.text());
            },
            complete: function(){
                username_loading.hide();
                username_input.get(0).setCustomValidity(username_notice.text());
            },
        });    
    });
    
    noid_jabatan_input.change(function () {
        console.log(noid_input.val() + " " + jabatan_input.val());
        noid_input.val(noid_input.val().trim());
        noid_notice.text("");
        var awalan_salah = false;
        
        if (noid_input.val().length == 0) {
            awalan_salah = true;
            noid_notice.text("Bagian ini harus diisi");
        } else if (!(/^[0-9]+$/.test(noid_input.val()))) {
            awalan_salah = true;
            noid_notice.text("Nomor identitas harus angka");
        }
        
        if (awalan_salah) {
            noid_input.get(0).setCustomValidity(noid_notice.text());
            return;
        }
        
        noid_loading.show();
        $.ajax({
            method: "POST",
            url: '{% url "registrasi:cek_noid_ada" %}',
            data: {
                'nomor_identitas': noid_input.val(),
                'jabatan': jabatan_input.val()
            },
            dataType: 'json',
            success: function (response) {
                console.log(response);
                if (response["hasil"] === "true") {
                    noid_notice.text("Nomor identitas sudah ada");
                }
                noid_input.get(0).setCustomValidity(noid_notice.text());
            },
            complete: function(){
                noid_input.get(0).setCustomValidity(noid_notice.text());
                noid_loading.hide();
            },
        });
    });
    
    tgl_lahir_input.change(function() {
        tgl_lahir_notice.val("");
        tanggal = $(this).val().trim();
        tgl_lahir_input.val(tanggal);
        if (tanggal.length == 0) {
            tgl_lahir_notice.text("Tanggal harus diisi");
        } else if (!validasi_tanggal(tanggal)) {
            tgl_lahir_notice.text("Tanggal tidak valid");
        }
        tgl_lahir_input.get(0).setCustomValidity(tgl_lahir_notice.text());
    });
    
    nohp_input.change(function() {
        nohp = $(this).val().trim();
        nohp_input.val(nohp);
        console.log(nohp.length);
        
        nohp_notice.text("");
        
        if (nohp.length != 0 && !(/^[0-9]+$/.test(nohp))) {
            nohp_notice.text("Nomor HP harus angka");
        }
        nohp_input.get(0).setCustomValidity(nohp_notice.text());
    });
});  
</script>
{% endblock %}