bmnc12/bmnc12/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
import beranda.urls as beranda

urlpatterns = [
    path('login/', include(('login.urls', 'login'), namespace="login")),
    path('registrasi/', include(('registrasi.urls', 'registrasi'), namespace="registrasi")),
    path('buat-berita/', include(('buat_berita.urls', 'buat_berita'), namespace="buat_berita")),
    path('polling-biasa/', include(('polling_biasa.urls', 'polling_biasa'), namespace="polling_biasa")),
    path('polling-berita/', include(('polling_berita.urls', 'polling_berita'), namespace="polling_berita")),
    path('personal-profile/', include(('personal_profile.urls', 'personal_profile'), namespace="personal_profile")),
    path('lihat-polling/', include(('lihat_polling.urls', 'lihat_polling'), namespace="lihat_polling")),
    path('', include(('beranda.urls', 'beranda'), namespace="")),
]

bmnc12/login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('otologin', views.otorisasi_login, name='otologin'),
    path('otologout', views.otorisasi_logout, name='otologout'),
]

bmnc12/login/models.py
from django.db import models

# Create your models here.

bmnc12/login/views.py
from django.shortcuts import render
from core.models import Pengguna
from django.db import connection,transaction
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.hashers import *

def index(request):
    if 'bmnc_user_login' in request.session.keys():
        return render(request, 'login/halaman-masuk-berhasil.html', {})
    response = {}
    response["render_registrasi"] = True
    return render(request, 'login/halaman-masuk.html', response)
    
def otorisasi_login(request):
    print ("#### Mencoba login")

    if request.method == "POST":
        username = request.POST['username'].strip()
        password = request.POST['password']
        
        print ("#### Login atas nama", username)
        
        id = None
        adalah_narasumber = False
        
        with connection.cursor() as cursor:
            cursor.execute("SELECT password, id FROM PENGGUNA WHERE username = %s", [username])
            row = cursor.fetchone()
            if row is None:
                print ("#### Login gagal, username mungkin tidak ada")
                messages.error(request, "Maaf, username atau password salah")
                return HttpResponseRedirect(reverse("login:index"))
            elif not check_password(password, row[0]):
                print ("#### Login gagal, username mungkin ada tapi pass salah")
                messages.error(request, "Maaf, username atau password salah")
                return HttpResponseRedirect(reverse("login:index"))
            else:
                id = row[1]                
                cursor.execute("SELECT * FROM NARASUMBER WHERE id = %s", [id])
                if cursor.fetchone() is not None:
                    adalah_narasumber = True
        request.session['adalah_narasumber'] = adalah_narasumber
        request.session['bmnc_user_login'] = username
        
        return render(request, 'login/halaman-masuk-berhasil.html', {})
    return HttpResponseRedirect(reverse('login:index'))

def otorisasi_logout(request):
    request.session.flush() # Menghapus semua session
    return HttpResponseRedirect(reverse('beranda:index'))

bmnc12/login/templates/login/halaman-masuk-berhasil.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="refresh" content="3;url={% url 'beranda:index' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static "/general/theme.css" %}"> </head>

<body>
  <nav class="navbar navbar-expand-lg bg-primary navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'beranda:index' %}"">
        <img src="{% static "/general/BMNC Logo Putih.svg" %}" width="50" height="50" class="d-inline-block align-top mx-1" alt="">
        <b>&nbsp;Biru Merah News Corporation</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="py-5" style="background-image: url('{% static "/general/bg-regis.jpg" %}');background-size:cover;background-repeat:space;">
    <div class="container">
      <div class="row">
        <div class="align-self-center col-md-6 text-white">
          
          <p class="lead" id="regis-subheader"><br><br>Login berhasil.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-dark text-white">
    <div class="container">
      <div class="row">
        <div class="p-4 col-md-6">
          <div class="col-md-12">
            <img class="img-fluid d-block" src="{% static "/general/BMNC Logo.svg" %}" width="120pt"> </div>
          <div class="row"> </div>
          <div class="row">
            <div class="col-md-12">
              <ul class="list-unstyled">
                <a href="{% url 'beranda:index' %}"" class="text-white">Beranda</a>
                <br>
                <a href="#" class="text-white">Tentang Kami</a>
                <br>
                <a href="#" class="text-white">Layanan</a>
                <br> </ul>
            </div>
          </div>
        </div>
        <div class="p-4 col-md-6">
          <h2 class="mb-4">Kontak</h2>
          <p>
            <a href="tel:+62 840 0840 0840" class="text-white">
              <i class="fa d-inline mr-3 text-secondary fa-phone"></i>+62 840 0840 0840</a>
          </p>
          <p>
            <a href="mailto:info@bmnc12.com" class="text-white">
              <i class="fa d-inline mr-3 text-secondary fa-envelope-o"></i>info@bmnc12.com</a>
          </p>
          <p>
            <a href="https://goo.gl/maps/MPqj51wBQSo" class="text-white" target="_blank">
              <i class="fa d-inline mr-3 fa-map-marker text-secondary"></i>Fakultas Ilmu Komputer, Universitas Indonesia </a>
            <br> </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 mt-3">
          <p class="text-center text-white">Hak Cipta © 2018 BMNC12 dilindungi undang-undang. </p>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script>
    $('#select-jabatan').on('change', function() {
    label_id = $('#form-label-nomor-id');
      if (this.value == 'M') {
        $('#form-status-label').text('Status Mahasiswa');
        $('#regis-groupstatus > input').attr("name", "status-mahasiswa");
        label_id.text('Nomor Identitas (NPM)');
      } else if (this.value == 'D') {
        $('#form-status-label').text('Jurusan Dosen');
        $('#regis-groupstatus > input').attr("name", "jurusan-dosen");
      } else if (this.value == 'S') {
        $('#form-status-label').text('Posisi Staf');
        $('#regis-groupstatus > input').attr("name", "posisi-staf");
      }
    })
  </script>
</body>

</html>

bmnc12/login/templates/login/halaman-masuk.html
{% extends "general/layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
  <div class="py-5" style="background-image: url({% static "general/bg-regis.jpg" %});">
    <div class="container">
      <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-6">
          <div class="card text-white p-5 bg-primary" id="login-card">
            <div class="card-body">
              <h1 class="mb-4">Masuk</h1>
              {% for message in messages %}
                <label style="position:relative; right:0px; text-align: right; display: block;" class="text-danger">
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
                    {{ message }}
                </label><br>
                {% endfor %}
              <form action="{% url 'login:otologin' %}" method="POST">
                    {% csrf_token %}
                <div class="form-group">
                  <label>Usernama</label>
                  <input type="text" class="form-control" placeholder="Masukkan usernama" required="" name="username"> </div>
                <div class="form-group">
                  <label>Kata Sandi</label>
                  <input type="password" class="form-control" placeholder="Masukkan kata sandi" name="password"> </div>
                <button type="submit" class="btn btn-secondary">Masuk</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}