bmnc12/bmnc12/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
import beranda.urls as beranda

urlpatterns = [
    path('login/', include(('login.urls', 'login'), namespace="login")),
    path('registrasi/', include(('registrasi.urls', 'registrasi'), namespace="registrasi")),
    path('buat-berita/', include(('buat_berita.urls', 'buat_berita'), namespace="buat_berita")),
    path('polling-biasa/', include(('polling_biasa.urls', 'polling_biasa'), namespace="polling_biasa")),
    path('polling-berita/', include(('polling_berita.urls', 'polling_berita'), namespace="polling_berita")),
    path('personal-profile/', include(('personal_profile.urls', 'personal_profile'), namespace="personal_profile")),
    path('lihat-polling/', include(('lihat_polling.urls', 'lihat_polling'), namespace="lihat_polling")),
    path('', include(('beranda.urls', 'beranda'), namespace="")),
]

bmnc12/login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('otologin', views.otorisasi_login, name='otologin'),
    path('otologout', views.otorisasi_logout, name='otologout'),
]

bmnc12/bmnc12/templates/general/partials/footer.html
{% load staticfiles %}
{% load static %}
<div class="bg-dark text-white">
<div class="container">
  <div class="row">
    <div class="p-4 col-md-6">
      <div class="col-md-12">
        <img class="img-fluid d-block" src="{% static "/general/BMNC Logo.svg" %}" width="120pt"> </div>
      <div class="row"> </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="">
            <a href="{% url 'beranda:index' %}"" class="text-white">Beranda</a>
            <br>
            <a href="#" class="text-white">Tentang Kami</a>
            <br>
            <a href="#" class="text-white">Layanan</a>
            <br> </ul>
        </div>
      </div>
    </div>
    <div class="p-4 col-md-6">
      <h2 class="mb-4">Kontak</h2>
      <p>
        <a href="tel:+62 840 0840 0840" class="text-white">
          <i class="fa d-inline mr-3 text-secondary fa-phone"></i>+62 840 0840 0840</a>
      </p>
      <p>
        <a href="mailto:info@bmnc12.com" class="text-white">
          <i class="fa d-inline mr-3 text-secondary fa-envelope"></i>info@bmnc12.com</a>
      </p>
      <p>
        <a href="https://goo.gl/maps/MPqj51wBQSo" class="text-white" target="_blank">
          <i class="fa d-inline mr-3 fa-map-marker text-secondary"></i>Fakultas Ilmu Komputer, Universitas Indonesia </a>
        <br> </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 mt-3">
      <p class="text-center text-white">Hak Cipta © 2018 BMNC12 dilindungi undang-undang. </p>
    </div>
  </div>
</div>
</div>

bmnc12/bmnc12/templates/general/partials/header.html
{% load staticfiles %}
{% load static %}
<nav class="navbar navbar-expand-lg bg-primary navbar-dark">
<div class="container">
  <a class="navbar-brand" href="{% url 'beranda:index' %}"">
    <img src="{% static "/general/BMNC Logo Putih.svg" %}" width="50" height="50" class="d-inline-block align-top mx-1" alt="">
    <b>&nbsp;Biru Merah News Corporation</b>
  </a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
    <ul class="navbar-nav">
    {% if not masuk %}
      {% if render_masuk %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login:index' %}">
              <i class="fa d-inline fa-lg fa-sign-in-alt"></i>&nbsp;Masuk</a>
          </li>
      {% endif %}
      {% if render_registrasi %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registrasi:index' %}">
              <i class="fa d-inline fa-lg fa-user-plus"></i> Registrasi</a>
          </li>
      {% endif %}
    {% else %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Profil </a>
        <span class="caret"></span>
        <ul class="dropdown-menu">
          <li>
            <a class="nav-link" href="{% url 'personal_profile:index' %}">
              <i class="fa d-inline fa-lg fa-user"></i>&nbsp; Lihat Profil</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'login:otologout' %}" onclick="return confirm('Keluar?')">
              <i class="fa d-inline fa-lg fa-sign-out-alt"></i>&nbsp;Keluar</a>
          </li>
        </ul>
      </li>
      {% if adalah_narasumber %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Berita </a>
        <span class="caret"></span>
        <ul class="dropdown-menu">
          <li>
            <a class="nav-link" href="#">
              <i class="fa d-inline fa-lg fa-list"></i>&nbsp; Berita Saya</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'buat_berita:index' %}" >
              <i class="fa d-inline fa-lg fa-plus"></i>&nbsp; Buat Berita</a>
          </li>
        </ul>
      </li>
      {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Polling </a>
        <span class="caret"></span>
        <ul class="dropdown-menu">
          <li>
            <a class="nav-link" href="{% url 'lihat_polling:index' %}">
              <svg width="20px" height="20px" viewBox="0 0 100 100" xml:space="preserve" enable-background="new 0 0 512 512">
                <path id="time-3-icon" d="M0,100c0-2.6,0-5.1,0-7.7c8.1,0,16.1,0,24.4,0C16.2,85.6,8.1,79,0,72.4C5.6,67,10.9,61.2,17,56.3
c8.2-6.8,12.9-15.2,16.7-24.3c2.2-5.2,4.8-10.3,7.3-15.4c0.2-0.3,0.6-0.7,1-0.8c15-5.1,30-10.5,45.2-15.2c3.8-1.2,8.5-0.2,12.9-0.2
c0,9.1,0,18.3,0,27.6c-1.9,0.9-3.9,2-6,2.6c-5.8,1.7-8.9,6-12.6,9.7c-3,3-6.9,5.4-10.3,8c2.9,2.3,6.4,5.2,9.9,8.1
C68.6,68.4,56.2,80.3,43.7,92.3c14.7,0,29.2,0,43.7,0c0,2.6,0,5.1,0,7.7C58.3,100,29.2,100,0,100z M46.4,32.7
C32.7,45.9,19,59,5.3,72.2c7.4,6.1,14.7,12,22.1,18c0.9,0.8,1.9,1.9,3,2c2.7,0.3,5.4,0.1,8.2,0.1c12.4-11.9,24.7-23.8,37.1-35.7
c-3-2.4-5.9-4.8-9-7.3c-4.7,2.8-9.4,5.6-14.1,8.4c-2.8,1.7-6,1.2-7.7-1.1c-1.7-2.3-0.8-5.1,2-6.7c4.1-2.3,8.2-4.5,12.3-6.8
C54.9,39.7,50.7,36.2,46.4,32.7z"></path>
              </svg> &nbsp; Lihat Polling</a>
          </li>
        {% if adalah_narasumber %}
          <li>
            <a class="nav-link" href="{% url 'polling_biasa:index' %}">
              <i class="fa d-inline fa-lg fa-plus"></i>&nbsp; Buat Polling Biasa</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'polling_berita:index' %}">
              <i class="fa d-inline fa-lg fa-plus"></i>&nbsp; Buat Polling Berita</a>
          </li>
        {% endif %}
        </ul>
      </li>
    {% endif %}
    {% block additional_navbar %}
    {% endblock %}
    </ul>
  </div>
</div>
</nav>